apiVersion: v1
kind: Service
metadata:
  name: {{.Owner.Name}}-service
  namespace: {{.Owner.Namespace}}
  labels:
    app: {{.Owner.Name}}
    component: {{.Owner.Name}}
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{.Owner.Name}}
    component: {{.Owner.Name}}
