apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrail
metadata:
  labels:
    app.kubernetes.io/name: trustyai-service-operator
    app.kubernetes.io/managed-by: kustomize
  name: nemoguardrail-sample
spec:
  nemoConfig: nemo-config-sample
  # OpenTelemetry tracing configuration
  tracing:
    serviceName: "my-nemo-guardrails"
    tracingEndpoint: "http://jaeger-collector.observability.svc.cluster.local:4317"
