apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.PluginsAdapter.Name}}
  namespace: {{.PluginsAdapter.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.PluginsAdapter.Name}}
  template:
    metadata:
      labels:
        app: {{.PluginsAdapter.Name}}
        app.kubernetes.io/part-of: trustyai
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: plugins-adapter
          image: {{.ContainerImages.PluginsAdapterImage}}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: MODEL_NAME # Currently only for logging.
              value: "dummy"
            - name: PLUGINS_SERVER_HOST
              value: "0.0.0.0"
            - name: PLUGINS_ENABLED
              value: "false"
            - name: PLUGINS_CLI_COMPLETION
              value: "false"
            - name: PLUGINS_CLI_MARKUP_MODE
              value: "rich"
            - name: PLUGINS_CONFIG
              value: "./resources/plugins/config.yaml"
            # - name: CHUK_MCP_CONFIG_PATH
              # value: "./resources/runtime/config.yaml"
            - name: MCP_SSL_ENABLED
              value: "false"
            - name: MCP_SSL_CERT_REQS
              value: "0"
            - name: LOGLEVEL
              value: "DEBUG"
            - name: PLUGINS_TRANSPORT
              value: "http"

          ports:
            - containerPort: 8000


