apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  selector:
    app: {{.Owner.Name}}
  ports:
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50052