kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.Orchestrator.Name}}
  namespace: {{.Orchestrator.Namespace}}
  labels:
    app: {{.Orchestrator.Name}}
    component: {{.Orchestrator.Name}}
    deploy-name: {{.Orchestrator.Name}}
    app.kubernetes.io/instance: {{.Orchestrator.Name}}
    app.kubernetes.io/name: {{.Orchestrator.Name}}
    app.kubernetes.io/part-of: trustyai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Orchestrator.Name}}
      component: {{.Orchestrator.Name}}
      deploy-name: {{.Orchestrator.Name}}
      app.kubernetes.io/instance: {{.Orchestrator.Name}}
      app.kubernetes.io/name: {{.Orchestrator.Name}}
      app.kubernetes.io/part-of: trustyai
  template:
    metadata:
      labels:
        app: {{.Orchestrator.Name}}
        component: {{.Orchestrator.Name}}
        deploy-name: {{.Orchestrator.Name}}
        app.kubernetes.io/instance: {{.Orchestrator.Name}}
        app.kubernetes.io/name: {{.Orchestrator.Name}}
        app.kubernetes.io/part-of: trustyai
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      volumes:
        - name: {{.Orchestrator.Name}}-config
          configMap:
            name: {{.Orchestrator.Spec.OrchestratorConfig}}
            defaultMode: 420
        {{if .Orchestrator.Spec.SidecarGatewayConfig}}
        - name: {{.Orchestrator.Name}}-sidecar-gateway-config
          configMap:
            name: {{.Orchestrator.Spec.SidecarGatewayConfig}}
            defaultMode: 420
        {{end}}
      serviceAccountName: {{.Orchestrator.Name}}-serviceaccount
      containers:
        - name: {{.Orchestrator.Name}}
          image: {{.ContainerImages.OrchestratorImage}}
          env:
            - name: ORCHESTRATOR_CONFIG
              value: /config/config.yaml
            {{if .Orchestrator.Spec.SidecarGatewayConfig}}
            - name: HTTP_PORT
              value: '8032'
            {{else}}
            - name: HTTP_PORT
              value: '8033'
            {{end}}
            - name: RUST_BACKTRACE
              value: 'full'
            - name: RUST_LOG
              value: 'info'
          {{if .Orchestrator.Spec.OTelExporter.OTLPProtocol}}
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: {{.Orchestrator.Spec.OTelExporter.OTLPProtocol}}
          {{end}}
          {{if .Orchestrator.Spec.OTelExporter.OTLPTracesEndpoint}}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{.Orchestrator.Spec.OTelExporter.OTLPTracesEndpoint}}
          {{end}}
          {{if .Orchestrator.Spec.OTelExporter.OTLPMetricsEndpoint}}
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: {{.Orchestrator.Spec.OTelExporter.OTLPMetricsEndpoint}}
          {{end}}
          {{if and .Orchestrator.Spec.OTelExporter.EnableTraces .Orchestrator.Spec.OTelExporter.EnableMetrics}}
            - name: OTLP_EXPORT
              value: "traces,metrics"
          {{else if .Orchestrator.Spec.OTelExporter.EnableTraces}}
            - name: OTLP_EXPORT
              value: "traces"
          {{else if .Orchestrator.Spec.OTelExporter.EnableMetrics}}
            - name: OTLP_EXPORT
              value: "metrics"
          {{end}}
          volumeMounts:
            - name: {{.Orchestrator.Name}}-config
              readOnly: true
              mountPath: /config/config.yaml
              subPath: config.yaml
          ports:
            {{if .Orchestrator.Spec.SidecarGatewayConfig}}
            - name: http
              containerPort: 8032
              protocol: TCP
            {{else}}
            - name: http
              containerPort: 8033
              protocol: TCP
            {{end}}
          imagePullPolicy: Always
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            readinessProbe:
              httpGet:
                path: /health
                port: 8033
                scheme: HTTP
              initialDelaySeconds: 10
              timeoutSeconds: 10
              periodSeconds: 20
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            command:
              - /app/bin/fms-guardrails-orchestr8
        {{if .Orchestrator.Spec.EnableGuardrailsGateway}}
        - name: {{.Orchestrator.Name}}-gateway
          image : {{.ContainerImages.GuardrailsGatewayImage}}
          command: ["/app/bin/vllm-orchestrator-gateway"]
          volumeMounts:
            - name: {{.Orchestrator.Name}}-sidecar-gateway-config
              readOnly: true
              mountPath: /config/config.yaml
              subPath: config.yaml
          env:
            - name: GATEWAY_CONFIG
              value: /config/config.yaml
        {{end}}
        {{if .Orchestrator.Spec.EnableBuiltInDetectors}}
        - name: {{.Orchestrator.Name}}-detectors
          image : {{.ContainerImages.DetectorImage}}
          command: ["/app/bin/regex-detector"]
        {{end}}
